# Generated by Django 6.1.2 on 2026-10-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField()),
                ('monto', models.PositiveIntegerField()),
                ('boletos', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('idavuelta', models.BooleanField()),
                ('monto', models.PositiveIntegerField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PaqueteTuristico', to='negocio.destino')),
            ],
        ),
    ]
